spring:
  application:
    name: AWS-BIGDATA-API

  #################
  ## JPA
  #################

  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
    generate-ddl: false
    show-sql: true
    properties:
      hibernate.hbm2ddl.import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
      hibernate.default_batch_fetch_size: ${chunkSize:1000}
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    open-in-view: false
    database: mysql

  #################
  ## DataSource
  #################

  datasource:
    url: jdbc:log4jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    connection-test-query: SELECT 1
    maximum-pool-size: 10
    minimum-idle: 3
    sql-script-encoding: UTF-8
    continue-on-error: true
    initialization-mode: always

  #################
  ## Auto Configure
  #################

  autoconfigure:
    exclude:

###################
## Web Container
###################

server:
  port: 8080
  address: 0.0.0.0

#################
## Application
#################

app:
  region-name: korea
  dynamo:
    datasource:
      oracle:
        url: jdbc:log4jdbc:oracle:thin:@localhost:1521:xe
        username: scott
        password: tiger
        driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
        connection-test-query: SELECT 1
        maximum-pool-size: 10
        minimum-idle: 3
        sql-script-encoding: UTF-8
        continue-on-error: true
        initialization-mode: always
      greenplum:
        url: jdbc:log4jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
        username: root
        password: root
        driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
        connection-test-query: SELECT 1
        maximum-pool-size: 10
        minimum-idle: 3
        sql-script-encoding: UTF-8
        continue-on-error: true
        initialization-mode: always
  s3:
    namenode: hdfs://192.168.1.1:8020
    hdfs-configuration-path:
      core-site: classpath:/core-site.xml
      hdfs-site: classpath:/hdfs-site.xml

#################
## Logging
#################

logging:
  level:
    root: INFO
    tomcat: INFO
    freemarker: INFO
    jdbc.connection: WARN
    jdbc.audit: WARN
    jdbc.sqlonly: WARN
    jdbc.resultset: WARN
    jdbc.resultsettable: DEBUG
    org.hibernate: INFO
    org.springframework: INFO
    org.springframework.session: WARN
    com.querydsl.sql: INFO
    org.apache: INFO
    com.zaxxer: INFO
    com.lg: DEBUG
  group:
    tomcat: org.apache.catalina, org.apache.coyote, org.apache.tomcat